export const desireOptions = [
  "swinging",
  "softswap",
  "polyamory",
  "bondage",
  "oralsex",
  "spanking",
  "hairpulling",
  "analsex",
  "blindfolds",
  "biting",
  "talkingdirty",
  "handcuffs",
  "lingerie",
  "discipline",
  "assplay",
  "collarandleadleash",
  "toys",
  "orgiesgroupsex",
  "candlewax",
  "breastnippleplay",
  "sexinpublic",
  "masturbation",
  "mutualmasturbation",
  "roleplay",
  "masterslave",
  "dildos",
  "vibrators",
  "eroticphotography",
  "pain",
  "highheels",
  "strap-ons",
  "humiliation",
  "whips",
  "exhibitionism",
  "rimming",
  "roughsex",
  "barebottomspanking",
  "nipples",
  "blowjobs",
  "breathplay",
  "voyeurism",
  "fisting",
  "sensorydeprivation",
  "gangbangs",
  "powerexchange",
  "makinghomemovies",
  "pantyhosestockings",
  "chains",
  "leather",
  "ageplay",
  "piercings",
  "watersports",
  "barehandedspanking",
  "facefucking",
  "cagingconfinement",
  "threesomes",
  "cunnilingus",
  "kissing",
  "deepthroating",
  "buttplugs",
  "intelligence",
  "latex",
  "orgasmcontrol",
  "cuddles",
  "multipleorgasms",
  "sugardaddysugarbaby",
  "chastitydevices",
  "domination",
  "chokingplay",
  "anal",
  "doublepenetration",
  "restraints",
  "sadism",
  "consensualnonconsentplay",
  "corsets",
  "tattoos",
  "masochism",
  "squirting",
  "fingering",
  "collars",
  "gaggingchokedbycock",
  "ballgags",
  "faceslapping",
  "footfeet",
  "masks",
  "ropebondagesuspension",
  "bdsm",
  "outdoorsex",
  "massages",
  "begging",
  "doctornurseplay",
  "crossdressing",
  "femaleejaculation",
  "obediencetraining",
  "orgasmdenial",
  "teasing",
  "cocksucking",
  "submission",
  "flogging",
  "cockandballtorture",
  "beltspanking",
  "daddygirl",
  "enemas",
  "costumesdressingup",
  "cockworship",
  "cuddling",
  "dating"
];

export const sexOptions = ["F", "M", "I", "MF", "FF", "MM", "II", "FI", "MI"];

export const genderOptions = ["F", "M", "I"];

export const distanceOptions = ["5", "10", "20", "50"];

export const langOptions = ["en", "es", "fr", "de"];

export const sexualityOptions = ["he", "ho", "bi", "pa", "qu", "as"];

export const eventTypeOptions = ["public", "private"];

export const biosOptions = [
  "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.",
  "If I had a flower for every time I thought of you, I could walk in my garden forever.",
  "Sometimes I’m not angry, I’m hurt and there’s a big difference.",
  "Do you believe in love at first sight, or should I walk by again?",
  "Fabulous ends in “us” coincidence? I think not.",
  "I want a cute, long relationship where everyone is like damn they’re still together?",
  "Try to be a rainbow in someone’s cloud.",
  "My life with you is something that I would never trade, even for all of the riches under heaven.",
  "All the blood, sweat, and tears will be worth it when I get to spend forever by your side.",
  "It’s funny how people say they miss you, but don’t even make an effort to see you.",
  "I’m not perfect. I’ll annoy you, make fun of you, say stupid things, but you’ll never find someone who loves you as much as I do.",
  "You’ll know they’re special when no matter what kind of mood you’re in, they can always manage to make you smile.",
  "To be brave is to love unconditionally without expecting anything in return.",
  "Sometimes, it’s better to be alone… No one can hurt you.",
  "If you dare, take my hand and take me to where your heart is. I want to feel what it’s like to love like you.",
  "When you love me like that, I melt into honey. Let’s be sweet together.",
  "The sweetest joy, the wildest woe is love.",
  "Why cry for someone when you can laugh next to someone else?",
  "The reason I like you is simple – love, laughter, and your smile.",
  "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
  "Please don’t forget to smile.",
  "Relationships these days start by pressing like on her photo.",
  "Awesome ends with ME and Ugly starts with You.",
  "Making the Snuggie look good since 2009.",
  "I’d rather spend one moment holding you than a lifetime knowing I never could.",
  "There is no other woman in the world like you. I am the luckiest man alive to be able to call you mine.",
  "I’ve fallen in love many times always with you.",
  "No matter what has happened. No matter what you’ve done. No matter what you will do. I will always love you. I swear it.",
  "Just a cupcake looking for a stud muffin.",
  "I don’t care how hard being together is, nothing is worse than being apart.",
  "The most painful goodbyes are those which were never said and never explained.",
  "I’ve realized that the Beatles got it wrong. Love isn’t all we need—love is all there is.",
  "You’re still a little kitten that looks at my eyes, wanting love in this cold world.",
  "I’ve been waiting hours and I’ll be waiting for hours more, till my love arrives and my heart’s fulfilled.",
  "When you fall for someone’s personality, almost everything about them becomes handsome and beautiful.",
  "Just about the time when you think you can make ends meet, somebody moves the ends.",
  "Before you, I never believed in forever. Now, I know that is not long enough to spend with you.",
  "Can anything be more valuable than our love? Since you are with me, my only measurement is in heartbeats.",
  "While heaven must surely mourn the loss of one of its own, we mere mortals celebrate your grace.",
  "When I miss you it seems every song I listen to is about you.",
  "An apple a day keeps the doctor away, but if the doctor is cute forget the fruit.",
  "Silence is the most powerful scream.",
  "Be yourself; everyone else is already taken.",
  "Sometimes you never realize the value of a moment until it becomes a memory.",
  "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
  "When I miss you I re-read our old conversations and smile like an idiot.",
  "Every time I see you I fall in love all over again.",
  "Everyone is beautiful in their own way because God makes no mistakes.",
  "My silence/smile is just another word for my pain.",
  "I don’t have much to give you. I’m not a rich man. What I can promise is that everything I do will be for you, always.",
  "Without you in my life, I would be incomplete. I pray that I should never know such pain.",
  "I love you with the breath, the smiles and the tears of all my life.",
  "If you can’t get someone out of your head. Maybe, they are supposed to be there.",
  "Perfect has 7 letters and so does meeeeee. Coincidence? I think not.",
  "If life is not smiling at you, give it a good tickling.",
  "Love is composed of a single soul inhabiting two bodies.",
  "No matter how strong of a person you are, there’s always someone who can make you weak.",
  "It hurts when you have someone in your heart but not in your arms."
];
